/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package semonster2;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("おはよう世界", classUnderTest.getGreeting());
    }
     @Test public void appHasAMonsters() {
        Monster classUnderTest = new Monster();
        assertNotNull("デュラハン", classUnderTest.printMonster(0));
        assertNotNull(4, classUnderTest.printRare(0));
    }
}