/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package semonster2;

public class App {
    public String getGreeting() {
        return "おはよう世界";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
